"""Formats check results into JSON, Markdown, and console output."""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any

SEVERITY_EMOJI = {
    "error": "🔴",
    "warning": "🟡",
    "info": "🔵",
    "exclusion": "⚪",
}


def to_json(results: dict[str, Any], output_path: Path) -> None:
    """Write results to a JSON file."""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(results, f, indent=2)


def _count_violations(results: dict[str, Any]) -> int:
    """Count total violations across schematics and PCBs."""
    total = 0
    for section in ("schematics", "pcbs"):
        for entry in results.get(section, []):
            total += entry.get("violation_count", 0)
    return total


def _render_violation(v: dict[str, Any]) -> list[str]:
    """Render a single violation as markdown list lines."""
    lines: list[str] = []
    severity = str(v.get("severity", "info")).lower()
    emoji = SEVERITY_EMOJI.get(severity, "⚪")
    v_type = v.get("type", "Unknown")
    description = v.get("description", "")
    lines.append(f"- {emoji} **{v_type}**: {description}")

    for item in v.get("items", []):
        item_desc = item.get("description", "")
        if item_desc:
            lines.append(f"  - {item_desc}")
    return lines


def _render_section(
    results: dict[str, Any],
    section: str,
    label: str,
) -> list[str]:
    """Render one section (schematics or pcbs) as markdown lines."""
    entries = results.get(section, [])
    if not entries:
        return []

    lines: list[str] = [f"### {label}", ""]
    for entry in entries:
        file_name = Path(entry["file"]).name
        count = entry.get("violation_count", 0)
        status = "✅" if count == 0 else "❌"

        lines.append("<details>")
        lines.append(
            f"<summary>{status} <code>{file_name}</code> — "
            f"{count} violation(s)</summary>"
        )
        lines.append("")

        if entry.get("error"):
            lines.append(f"> ⚠️ {entry['error']}")
            lines.append("")

        for v in entry.get("violations", []):
            lines.extend(_render_violation(v))

        lines.append("")
        lines.append("</details>")
        lines.append("")

    return lines


def to_markdown(results: dict[str, Any]) -> str:
    """Format results as a Markdown comment for a GitHub PR."""
    lines: list[str] = ["## 🔍 design-diff-bot Report", ""]

    if not results.get("kicad_cli_available", True):
        lines.append("> ⚠️ `kicad-cli` was not found on PATH. "
                     "No checks were run.")
        lines.append("")
        lines.append("---")
        lines.append(
            "*Generated by [design-diff-bot]"
            "(https://github.com/amrmuhammad/design-diff-bot)*"
        )
        return "\n".join(lines)

    total = _count_violations(results)

    if total == 0:
        lines.append("✅ **No violations found.** Design looks clean.")
        lines.append("")
        lines.append("---")
        lines.append(
            "*Generated by [design-diff-bot]"
            "(https://github.com/amrmuhammad/design-diff-bot)*"
        )
        return "\n".join(lines)

    lines.append(f"**Total violations:** {total}")
    lines.append("")

    lines.extend(_render_section(results, "schematics", "Schematics (ERC)"))
    lines.extend(_render_section(results, "pcbs", "PCBs (DRC)"))

    lines.append("---")
    lines.append(
        "*Generated by [design-diff-bot]"
        "(https://github.com/amrmuhammad/design-diff-bot)*"
    )
    return "\n".join(lines)
